Fix formatting
dataiku/dss-plugin-nlp-google-cloud-translation pull request #3
Opened 2021-07-16 13:00 UTC by Muennighoff

The GCloud translation API exposes a parameter for formatting, which by default is set to "html". This default assumes that the input text is HTML, which leads to the output being misformatted for special characters, such as in French:

J'aime becomes J&#39;aime

This PR sets the default to "text", as our users are more likely to have plain text rather than HTML data. The PR makes it configurable via the recipe.json.

References:
- https://googleapis.dev/python/translation/latest/_modules/google/cloud/translate_v2/client.html#Client.translate
- https://googleapis.dev/python/translation/latest/client.html

2021-07-19 09:06 UTC, arnaudde approved these changes
I did not test the behavior but the code lgtm 👍

2021-07-20 08:27 UTC, alexcombessie requested changes
LGTM! A few small UI wording suggestions.

2021-07-20 08:27 UTC, alexcombessie commented on custom-recipes/nlp-google-cloud-translation-translate/recipe.json
> +      "label": "Input Format",
Nitpick: harmonize case
```suggestion
      "label": "Input format",
```

2021-07-20 08:27 UTC, alexcombessie commented on custom-recipes/nlp-google-cloud-translation-translate/recipe.json
> +      "mandatory": false,
```suggestion
      "mandatory": true,
```

2021-07-20 08:27 UTC, alexcombessie commented on custom-recipes/nlp-google-cloud-translation-translate/recipe.json
> +          "label": "text"
```suggestion
          "label": "Text"
```

2021-07-20 08:27 UTC, alexcombessie commented on custom-recipes/nlp-google-cloud-translation-translate/recipe.json
> +          "label": "html"
```suggestion
          "label": "HTML"
```

2021-07-20 08:28 UTC, alexcombessie commented
By the way, don't forget to increase the version number by 0.0.1 before releasing

2021-07-20 08:34 UTC, alexcombessie approved these changes

2021-07-20 08:35 UTC, alexcombessie commented
... and add changes to the CHANGELOG

2021-07-20 08:36 UTC, Muennighoff commented
> ... and add changes to the CHANGELOG

Good to merge?

2021-07-20 08:42 UTC, alexcombessie commented on CHANGELOG.md
> +- 🐛 Fixed formatting to default to Text and allow changing to HTML to avoid escaping of characters like '
```suggestion
- 🐛 Fixed default input format to Text instead of HTML to avoid escaping special characters e.g., ' → &#39
```

2021-07-20 08:46 UTC, alexcombessie commented
... and remember to update the doc on https://www-preprod.dataiku.com/wp-admin/
I did it for the plugin info table, you need to update the screenshots and the usage doc with the new parameter.

2021-07-20 10:40 UTC, merged